#!/usr/bin/env python3
"""
Selects a consolidated wildfire (from planilha_fogos_consolidados.csv,
generated by generate_spreadsheet.py) and generates its visual dashboard via rtdash.py.
"""
import sys
import unicodedata
import webbrowser
from datetime import datetime
from pathlib import Path

import pandas as pd

PROJECT_DIR = Path(__file__).parent.resolve()
geodata_dir = PROJECT_DIR / "geodata"
if str(geodata_dir) not in sys.path:
    sys.path.insert(0, str(geodata_dir))

from ai_assistant import ask_suggestion, build_prompt
from rtdata_main import coletar_tudo, imprimir_resumo
from rtdash import salvar_dashboard

def remove_accents(text: str) -> str:
    normalized = unicodedata.normalize("NFKD", text)
    return "".join(c for c in normalized if not unicodedata.combining(c)).lower()


def load_hotspots() -> pd.DataFrame:
    path = PROJECT_DIR / "planilha_fogos_consolidados.csv"
    if not path.exists():
        print(f"Error: '{path.name}' not found. Run 'python generate_spreadsheet.py' first.", file=sys.stderr)
        sys.exit(1)
    df = pd.read_csv(path)
    
    for column in ("municipio", "bioma"):
        if column not in df.columns:
            df[column] = ""
    return df.sort_values("qtd_focos", ascending=False).reset_index(drop=True)


def _clean(value, empty_placeholder="—") -> str:
    text = str(value) if value is not None else ""
    return empty_placeholder if text.strip().lower() in ("nan", "none", "") else text


def show_list(df: pd.DataFrame) -> None:
    print(f"\n{'#':>4}  {'Date':<12} {'Municipality':<25} {'Biome':<15} {'Hotspots':>8}")
    print("-" * 70)
    for i, row in df.head(30).iterrows():
        municipality = _clean(row.get("municipio"))[:24]
        biome = _clean(row.get("bioma"))[:14]
        print(f"{i:>4}  {row['data_pura']:<12} {municipality:<25} {biome:<15} {int(row['qtd_focos']):>8}")
    if len(df) > 30:
        print(f"... and {len(df) - 30} more hotspots (use search to filter)")


def main() -> None:
    df_all = load_hotspots()
    df_current = df_all

    while True:
        show_list(df_current)
        print(
            "\nEnter a hotspot number to view details, "
            "a search term (municipality or date YYYY-MM-DD), "
            "'clear' to reset filters, or 'exit':"
        )
        user_input = input("> ").strip()

        if user_input.lower() in ("exit", "quit", "q", "sair"):
            break
        if user_input.lower() == "clear":
            df_current = df_all
            continue

        if user_input.isdigit():
            index = int(user_input)
            if index not in df_current.index:
                print("Invalid number — please choose one from the displayed list.")
                continue
            row = df_current.loc[index]
            lat, lon = float(row["lat_fogo"]), float(row["lon_fogo"])
            date_time = datetime.fromisoformat(f"{row['data_pura']}T12:00:00")

            print(f"\nCollecting data for {row.get('municipio', '—')} ({lat}, {lon}) on {row['data_pura']}...")
            data = coletar_tudo(lat, lon, data_hora=date_time)
            imprimir_resumo(data)

            dashboard_path = salvar_dashboard(data)
            print(f"Dashboard saved at: {dashboard_path}")
            webbrowser.open(f"file://{Path(dashboard_path).resolve()}")

            neighboring_species = str(row.get("especies_vizinhas", "") or "")
            spreadsheet_biome = str(row.get("bioma", "") or "")
            if spreadsheet_biome.strip().lower() in ("nan", "none", ""):
                spreadsheet_biome = ""
                
            print("\nConsulting AI for reforestation recommendations...")
            prompt = build_prompt(
                data, neighboring_species,
                municipality=str(row.get("municipio", "")),
                reliable_biome=spreadsheet_biome,
            )
            suggestion = ask_suggestion(prompt)
            print("\n" + "=" * 70)
            print(" AI SUGGESTION")
            print("=" * 70)
            print(suggestion)
            continue

        # Any other text: filter by municipality or date
        if user_input:
            term = remove_accents(user_input)
            df_current = df_all[
                df_all["municipio"].astype(str).apply(remove_accents).str.contains(term, na=False)
                | df_all["data_pura"].astype(str).str.contains(user_input, na=False)
            ].reset_index(drop=True)
        else:
            df_current = df_all

        if df_current.empty:
            print(f"No hotspots found for '{user_input}'. Showing all items again.")
            df_current = df_all


if __name__ == "__main__":
    main()