#!/usr/bin/env python3
"""
Selects a consolidated wildfire (from planilha_fogos_consolidados.csv,
generated by generate_spreadsheet.py) and generates its visual dashboard
via rtdash.py, then runs the deterministic species/biocapsule-dosage
recommendation via motor_decision.py (no LLM involved).
"""
import sys
import json
import unicodedata
import webbrowser
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

PROJECT_DIR = Path(__file__).parent.resolve()
ENRICHED_SPREADSHEET_PATH = PROJECT_DIR / "enriched_hotspots.csv"

# rtdata.py / rtdash.py / motor_decision.py normally live alongside this
# script, but some setups keep them in a "geodata/" subfolder — add it to
# sys.path so the imports below resolve either way.
geodata_dir = PROJECT_DIR / "geodata"
if str(geodata_dir) not in sys.path:
    sys.path.insert(0, str(geodata_dir))

# species.json lives next to motor_decision.py — check the geodata/
# subfolder first, then fall back to the project root.
SPECIES_JSON_PATH = (
    geodata_dir / "species.json" if (geodata_dir / "species.json").exists()
    else PROJECT_DIR / "species.json"
)

from rtdata import collect_all, print_summary
from rtdash import save_dashboard
import motor_decision as engine


def remove_accents(text: str) -> str:
    normalized = unicodedata.normalize("NFKD", text)
    return "".join(c for c in normalized if not unicodedata.combining(c)).lower()


def load_hotspots() -> pd.DataFrame:
    path = PROJECT_DIR / "planilha_fogos_consolidados.csv"
    if not path.exists():
        print(f"Error: '{path.name}' not found. Run 'python generate_spreadsheet.py' first.", file=sys.stderr)
        sys.exit(1)
    df = pd.read_csv(path)

    for column in ("municipio", "bioma"):
        if column not in df.columns:
            df[column] = ""
    return df.sort_values("qtd_focos", ascending=False).reset_index(drop=True)


def _clean(value, empty_placeholder="—") -> str:
    text = str(value) if value is not None else ""
    return empty_placeholder if text.strip().lower() in ("nan", "none", "") else text


def _value(data: dict, section: str, field: str, default=None):
    """Safely extract a field from one collector section."""
    value = data.get(section, {})
    return value.get(field, default) if isinstance(value, dict) else default


def save_enriched_hotspot(row: pd.Series, data: dict, dashboard_path: str) -> None:
    """Upsert one API-enriched wildfire in the cumulative CSV spreadsheet."""
    protected_areas = data.get("nearby_protected_areas") or []
    fire_history = data.get("local_fire_history") or {}
    nearest_water = _value(data, "water_distance", "nearest_water_body", {}) or {}
    nearest_vegetation = _value(data, "native_vegetation_distance", "nearest_vegetation_fragment", {}) or {}

    # `collect_all` is called with a specific datetime, so climate comes
    # back under "historical_weather" rather than "current_weather_and_forecast".
    climate = data.get("historical_weather") or {}

    record = row.to_dict()
    record.update({
        "consolidated_fire_id": f"{row['data_pura']}|{float(row['lat_fogo']):.6f}|{float(row['lon_fogo']):.6f}",
        "enriched_at_utc": datetime.now(timezone.utc).isoformat(),
        "dashboard_file": str(Path(dashboard_path).resolve()),
        "municipality_api": _value(data, "location", "municipality"),
        "state_api": _value(data, "location", "state"),
        "biome_api": _value(data, "biome_and_vegetation", "biome"),
        "original_vegetation_api": _value(data, "biome_and_vegetation", "original_vegetation"),
        "elevation_m_api": _value(data, "elevation_and_timezone", "elevation_m"),
        "temperature_c_api": climate.get("temperature_c"),
        "relative_humidity_pct_api": climate.get("relative_humidity_pct"),
        "precipitation_mm_api": climate.get("precipitation_mm"),
        "wind_kmh_api": climate.get("wind_kmh"),
        "pm2_5_api": _value(data, "air_quality", "pm2_5"),
        "pm10_api": _value(data, "air_quality", "pm10"),
        "slope_pct_api": _value(data, "slope_relief", "estimated_slope_pct"),
        "relief_classification_api": _value(data, "slope_relief", "relief_classification"),
        "erosion_risk_api": _value(data, "erosion_risk", "erosion_risk_class"),
        "land_use_api": _value(data, "land_use", "land_use") or _value(data, "land_use", "mapbiomas_class_code"),
        "nearest_water_body": nearest_water.get("name"),
        "water_distance_km": nearest_water.get("distance_km"),
        "nearest_native_vegetation": nearest_vegetation.get("name"),
        "native_vegetation_distance_km": nearest_vegetation.get("distance_km"),
        "nearby_protected_areas_count": len(protected_areas),
        "nearby_protected_areas": "; ".join(str(area.get("name", "")) for area in protected_areas),
        "fire_hotspots_in_radius": fire_history.get("total_hotspots_in_radius"),
        "fire_history_years": "; ".join(map(str, fire_history.get("years_with_records", []))),
        "enrichment_errors": json.dumps(data.get("errors", {}), ensure_ascii=False),
        "enriched_data_json": json.dumps(data, ensure_ascii=False),
    })

    new_df = pd.DataFrame([record])
    if ENRICHED_SPREADSHEET_PATH.exists():
        existing_df = pd.read_csv(ENRICHED_SPREADSHEET_PATH)
        if "consolidated_fire_id" in existing_df.columns:
            existing_df = existing_df[existing_df["consolidated_fire_id"] != record["consolidated_fire_id"]]
        new_df = pd.concat([existing_df, new_df], ignore_index=True, sort=False)

    new_df.to_csv(ENRICHED_SPREADSHEET_PATH, index=False)
    print(f"Enriched data saved to: {ENRICHED_SPREADSHEET_PATH.name}")


def print_biocapsule_recommendation(recommendation: dict) -> None:
    print("\n" + "=" * 70)
    print(" BIOCAPSULE RECOMMENDATION (geodata scoring engine)")
    print("=" * 70)
    print(f"Soil pH at point: {recommendation['point_soil_ph']}")
    print(f"Estimated annual precipitation: {recommendation['point_annual_precipitation_mm']} mm")
    for i, rec in enumerate(recommendation["recommendations"], start=1):
        print(f"\n#{i} {rec['species']} ({rec['scientific_name']}) — score {rec['final_score']}")
        print(f"    Sub-scores: {rec['sub_scores']}")
        dosage = rec["capsule_dosage"]
        print(f"    Suggested dosage: {dosage['biochar_g']} g biochar | {dosage['hydrogel_g']} g hydrogel")
        print(f"    Source: {rec['source']}")


def show_list(df: pd.DataFrame) -> None:
    print(f"\n{'#':>4}  {'Date':<12} {'Municipality':<25} {'Biome':<15} {'Hotspots':>8}")
    print("-" * 70)
    for i, row in df.head(30).iterrows():
        municipality = _clean(row.get("municipio"))[:24]
        biome = _clean(row.get("bioma"))[:14]
        print(f"{i:>4}  {row['data_pura']:<12} {municipality:<25} {biome:<15} {int(row['qtd_focos']):>8}")
    if len(df) > 30:
        print(f"... and {len(df) - 30} more hotspots (use search to filter)")


def main() -> None:
    df_all = load_hotspots()
    df_current = df_all

    while True:
        show_list(df_current)
        print(
            "\nEnter a hotspot number to view details, "
            "a search term (municipality or date YYYY-MM-DD), "
            "'clear' to reset filters, or 'exit':"
        )
        user_input = input("> ").strip()

        if user_input.lower() in ("exit", "quit", "q", "sair"):
            break
        if user_input.lower() == "clear":
            df_current = df_all
            continue

        if user_input.isdigit():
            index = int(user_input)
            if index not in df_current.index:
                print("Invalid number — please choose one from the displayed list.")
                continue
            row = df_current.loc[index]
            lat, lon = float(row["lat_fogo"]), float(row["lon_fogo"])
            date_time = datetime.fromisoformat(f"{row['data_pura']}T12:00:00")

            print(f"\nCollecting data for {row.get('municipio', '—')} ({lat}, {lon}) on {row['data_pura']}...")
            data = collect_all(lat, lon, dt=date_time)
            print_summary(data)

            dashboard_path = save_dashboard(data)
            save_enriched_hotspot(row, data, dashboard_path)
            print(f"Dashboard saved at: {dashboard_path}")
            webbrowser.open(f"file://{Path(dashboard_path).resolve()}")

            print("\nScoring species with the geodata decision engine...")
            recommendation = engine.recommend_biocapsule(
                data,
                species_path=str(SPECIES_JSON_PATH),
            )
            print_biocapsule_recommendation(recommendation)
            continue

        # Any other text: filter by municipality or date
        if user_input:
            term = remove_accents(user_input)
            df_current = df_all[
                df_all["municipio"].astype(str).apply(remove_accents).str.contains(term, na=False)
                | df_all["data_pura"].astype(str).str.contains(user_input, na=False)
            ].reset_index(drop=True)
        else:
            df_current = df_all

        if df_current.empty:
            print(f"No hotspots found for '{user_input}'. Showing all items again.")
            df_current = df_all


if __name__ == "__main__":
    main()